vich_uploader:
    db_driver: orm

    mappings:
      artwork:
        uri_prefix: /images/artworks
        upload_destination: '%kernel.project_dir%/public/images/artworks'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    metadata:
        type: attribute